spring.application.name=StudentManagement

spring.datasource.url=jdbc:mysql://localhost:3306/StudentManagement0816
spring.datasource.username=root
spring.datasource.password=oguro2124
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
mybatis.configuration.map-underscore-to-camel-case=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true
